#include "AsmWriter.h"
#include "./../klib/Kfile.h"
#include "./../app_constants.h"
#include "script_constants.h"
#include <format>

void script::AsmWriter::write_asm_file(const ht::ScriptConfig& config, const AsmView& view,
	const std::string& out_filename) const {
	
	const auto get_domain_comment = [](script::ArgDomain d) -> std::string {
		switch (d) {
		case script::ArgDomain::Flag: return " ; flags / items";
		case script::ArgDomain::NPC:  return " ; npc ids";
		default:                      return " ; values";
		}
		};
	
	std::string out_asm{
		std::format(" ; Battle of Olympus Script Layer assmebly file generated by {} version {}\n ; {}\n\n{}\n",
			ht::appc::APP_NAME, ht::appc::APP_VERSION, ht::appc::APP_URL, c::ASM_SECTION_DEFINES)
	};

	for (const auto& kv : config.defines) {
		out_asm += std::format("\n{}\n", get_domain_comment(kv.first));
		for (const auto& defv : kv.second) {
			out_asm += std::format("define {} ${:02x}\n", defv.second, defv.first);
		}
	}

	out_asm += std::format("\n{}\n", c::ASM_SECTION_SCRIPT);

	// code section
	bool last_was_ep{ false };
	for (const auto& line : view.lines) {

		if (line.type == AsmView::LineType::Directive) {
			if (!last_was_ep) {
				out_asm += "\n";
				last_was_ep = true;
			}

			out_asm += line.segments.at(0).text + "\n";
			continue;
		}
		else if (line.type == AsmView::LineType::Label)
			out_asm += line.segments.at(0).text + "\n";
		else {
			out_asm += "  ";

			for (std::size_t j{ 0 }; j < line.segments.size(); ++j) {
				const auto& seg{ line.segments[j] };

				if (seg.kind == AsmView::SegmentKind::String)
					out_asm += std::format("\"{}\"", seg.text);
				else
					out_asm += seg.text;

				if (j + 1 != line.segments.size())
					out_asm += " ";
			}

			out_asm += "\n";
		}

		last_was_ep = false;
	}

	klib::file::write_string_to_file(out_asm, out_filename);
}
